"""Expand cinematic corpus from 153 to 200+ techniques."""
import json
import sys

CORPUS_PATH = "/Users/ted/vivid/backend/data/rag_docs/cinematic/techniques_corpus.json"

NEW_TECHNIQUES = [
    # === aesthetic_style (NEW CATEGORY) ===
    {"technique_id":"solapunk","category":"aesthetic_style","name_ko":"솔라펑크","name_en":"Solapunk","description_ko":"친환경 미래 미학. 태양광, 식물, 유기적 건축이 어우러진 유토피안 비전.","visual_effect_ko":"희망적 미래, 유기적 기술, 자연과 기술의 조화","best_for":["utopia","eco_future","hopeful_sci_fi"],"prompt_keywords":{"kling":"solarpunk aesthetic, lush greenery with solar panels, organic architecture","seedance":"solarpunk utopian cityscape, bio-integrated technology, verdant rooftop gardens","veo":"Wide shot on 24mm lens: solarpunk city with organic architecture, lush vertical gardens, warm golden sunlight, bio-integrated solar technology, hopeful utopian atmosphere"},"combinable_with":["natural_golden_hour","crane_up","warm_desaturated"],"source_refs":["web_research_2026"],"multi_shot_hint":"opener"},
    {"technique_id":"biopunk","category":"aesthetic_style","name_ko":"바이오펑크","name_en":"Biopunk","description_ko":"생체공학과 유기체 기반 기술 미학. 생물학적 변형과 바이오테크 디스토피아.","visual_effect_ko":"유기적 공포, 생물학적 변형, 습하고 어두운 분위기","best_for":["horror","sci_fi","dystopia"],"prompt_keywords":{"kling":"biopunk aesthetic, organic technology, bioluminescent growths on machinery","seedance":"biopunk laboratory, biological augmentation, wet organic surfaces with dim green bioluminescence","veo":"Medium shot on 50mm lens: biopunk environment with organic technology, bioluminescent tendrils, wet humid atmosphere, green-tinted shadows"},"combinable_with":["low_key_lighting","slow_push_in","cool_blue"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    {"technique_id":"wes_anderson_flat","category":"aesthetic_style","name_ko":"웨스 앤더슨 스타일","name_en":"Wes Anderson Flat","description_ko":"파스텔 색조, 완벽한 좌우 대칭, 플랫 라이팅. 스토리북 미학.","visual_effect_ko":"동화적 세계관, 정교한 인위성, 유머러스한 아름다움","best_for":["comedy","whimsy","character_introduction"],"prompt_keywords":{"kling":"Wes Anderson style, pastel color palette, perfectly symmetrical flat composition","seedance":"Wes Anderson aesthetic, dollhouse symmetry, candy-colored palette, flat frontal framing","veo":"Locked wide shot on 40mm lens: perfectly centered bilateral symmetry, pastel palette, flat even lighting, storybook production design, deadpan staging"},"combinable_with":["symmetric_composition","high_key_lighting","pastel_palette"],"source_refs":["web_research_2026"],"multi_shot_hint":"opener"},
    {"technique_id":"film_noir_neo","category":"aesthetic_style","name_ko":"네오 누아르","name_en":"Neo Noir","description_ko":"고전 필름 누아르의 현대적 재해석. 네온 + 그림자 + 도시 밤.","visual_effect_ko":"도시적 위험, 도덕적 모호함, 스타일리시한 어둠","best_for":["crime","mystery","night_scene"],"prompt_keywords":{"kling":"neo noir style, neon reflections on wet streets, deep shadows with colored highlights","seedance":"neo noir cityscape, rain-slicked streets reflecting neon, high contrast shadows with magenta accents","veo":"Medium shot on 50mm lens: neo noir urban night, rain-wet asphalt reflecting neon signs, deep contrasty shadows, magenta and cyan color accents, morally ambiguous atmosphere"},"combinable_with":["chiaroscuro","neon_saturated","low_angle"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"cyberpunk_neon","category":"aesthetic_style","name_ko":"사이버펑크 네온","name_en":"Cyberpunk Neon","description_ko":"네온 조명이 지배하는 디스토피안 미래 도시. 기술과 퇴폐의 공존.","visual_effect_ko":"기술적 과잉, 네온 과포화, 미래적 퇴폐","best_for":["sci_fi","action","night_urban"],"prompt_keywords":{"kling":"cyberpunk neon city, holographic advertisements, dense urban dystopia","seedance":"cyberpunk metropolis drenched in neon, holographic billboards, crowded rain-soaked streets","veo":"Wide shot on 24mm lens: cyberpunk megacity, dense neon signage, holographic ads, rain-soaked streets reflecting pink and blue light, dystopian urban density"},"combinable_with":["neon_saturated","dutch_angle","handheld_shaky"],"source_refs":["web_research_2026"],"multi_shot_hint":"opener"},
    {"technique_id":"steampunk","category":"aesthetic_style","name_ko":"스팀펑크","name_en":"Steampunk","description_ko":"빅토리안 산업혁명 미학. 황동, 증기, 기계장치, 따뜻한 금속 톤.","visual_effect_ko":"기계적 경이, 빅토리안 화려함, 따뜻한 금속 질감","best_for":["fantasy","adventure","period"],"prompt_keywords":{"kling":"steampunk aesthetic, brass gears and copper pipes, Victorian industrial machinery","seedance":"steampunk workshop, brass clockwork mechanisms, warm copper tones with steam wisps","veo":"Medium shot on 35mm lens: steampunk interior with brass gears and copper pipes, warm amber lighting, steam wisps, Victorian industrial grandeur"},"combinable_with":["warm_desaturated","rim_light","foreground_layering"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"vaporwave","category":"aesthetic_style","name_ko":"베이퍼웨이브","name_en":"Vaporwave","description_ko":"80~90년대 레트로퓨처리즘. 핑크/시안 그라디언트, 로마 조각상, 디지털 그리드.","visual_effect_ko":"레트로 노스탤지어, 디지털 초현실, 신비로운 분위기","best_for":["music_video","abstract","nostalgia"],"prompt_keywords":{"kling":"vaporwave aesthetic, pink and cyan gradients, Roman bust statues, digital grid landscape","seedance":"vaporwave dreamscape, sunset gradient sky, marble statues, retro digital grid, palm tree silhouettes","veo":"Wide shot on 35mm lens: vaporwave landscape with pink-to-cyan gradient sky, marble bust sculpture, digital grid floor, palm tree silhouettes, dreamy retro-futurist atmosphere"},"combinable_with":["neon_saturated","pastel_palette","slow_dissolve"],"source_refs":["web_research_2026"],"multi_shot_hint":"opener"},
    # === camera_movement (new additions) ===
    {"technique_id":"crash_zoom","category":"camera_movement","name_ko":"크래시 줌","name_en":"Crash Zoom","description_ko":"극도로 빠른 줌인/줌아웃. 충격, 서프라이즈, 코미디 타이밍에 사용.","visual_effect_ko":"충격적 강조, 코믹 타이밍, 즉각적 주의 집중","best_for":["comedy","surprise","action_beat"],"prompt_keywords":{"kling":"crash zoom in on subject, ultra-fast zoom snap, sudden magnification","seedance":"violent crash zoom snapping onto subject, abrupt focal length shift, comedic emphasis zoom","veo":"Crash zoom on 70-200mm lens: ultra-rapid zoom snap onto subject's face, sudden dramatic magnification, comedic or shocking emphasis"},"combinable_with":["whip_pan","rapid_cuts","dutch_angle"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    {"technique_id":"vertigo_effect","category":"camera_movement","name_ko":"버티고 이펙트 (돌리 줌)","name_en":"Vertigo Effect / Dolly Zoom","description_ko":"돌리 인 + 줌 아웃 (또는 반대) 동시 실행. 배경 왜곡으로 불안감 극대화.","visual_effect_ko":"공간 왜곡, 극심한 불안, 초현실적 긴장","best_for":["horror","realization","psychological_tension"],"prompt_keywords":{"kling":"dolly zoom vertigo effect, background warping while subject stays same size, Hitchcock zoom","seedance":"vertigo dolly-zoom effect, simultaneous dolly-in and zoom-out creating spatial distortion, Hitchcock-inspired perspective warp","veo":"Dolly zoom on 50mm lens: camera pushing forward while lens zooms out, background compressing and warping around stationary subject, vertigo-inducing spatial distortion"},"combinable_with":["slow_push_in","chiaroscuro","dutch_angle"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    {"technique_id":"fpv_drone_dive","category":"camera_movement","name_ko":"FPV 드론 다이브","name_en":"FPV Drone Dive","description_ko":"1인칭 드론 시점의 고속 하강/관통 촬영. 극한 역동성과 몰입감.","visual_effect_ko":"극한 속도감, 관통하는 몰입, 아드레날린","best_for":["action","establishing_shot","extreme_sports"],"prompt_keywords":{"kling":"FPV drone dive through environment, first-person aerial plunge, high-speed threading through obstacles","seedance":"FPV drone racing perspective, diving through narrow gaps at high speed, first-person aerial threading","veo":"FPV drone shot on ultra-wide lens: high-speed dive through environment, threading between obstacles, first-person aerial perspective, extreme velocity motion blur"},"combinable_with":["bird_eye","whip_pan","speed_ramp"],"source_refs":["web_research_2026"],"multi_shot_hint":"opener"},
    {"technique_id":"parallax_scroll","category":"camera_movement","name_ko":"패럴랙스 스크롤","name_en":"Parallax Scroll","description_ko":"전경/중경/후경이 다른 속도로 이동하며 깊이감 생성. 2.5D 효과.","visual_effect_ko":"입체적 깊이, 레이어드 공간감, 그래픽 노블 미학","best_for":["title_sequence","storytelling","depth_staging"],"prompt_keywords":{"kling":"parallax scrolling effect, layered depth planes moving at different speeds, 2.5D motion","seedance":"parallax depth layers scrolling independently, foreground sliding faster than background, dimensional depth illusion","veo":"Lateral tracking on 35mm lens: parallax layers moving at different speeds, foreground rushing past while background glides slowly, 2.5D dimensional depth effect"},"combinable_with":["foreground_layering","lateral_tracking","frame_within_frame"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"lens_whacking","category":"camera_movement","name_ko":"렌즈 웨킹","name_en":"Lens Whacking / Free Lensing","description_ko":"렌즈를 본체에서 분리/기울여 촬영. 불규칙 보케, 광선 누출, 초현실적 포커스.","visual_effect_ko":"광선 누출, 유기적 보케, 몽환적 불규칙","best_for":["dream_sequence","memory","music_video"],"prompt_keywords":{"kling":"free-lensing effect, light leaks with irregular bokeh, dreamy unfocused edges","seedance":"lens whacking aesthetic, organic light leaks bleeding across frame, irregular selective focus with ethereal bokeh","veo":"Close-up on detached 50mm lens: light leak streaks bleeding across frame, irregular tilt-shift focus, dreamy organic bokeh, ethereal memory-like quality"},"combinable_with":["soft_diffused_light","slow_dissolve","natural_golden_hour"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    # === lighting (new additions) ===
    {"technique_id":"bisexual_lighting","category":"lighting","name_ko":"바이섹슈얼 라이팅","name_en":"Bisexual Lighting","description_ko":"핑크와 블루 네온이 양쪽에서 비추는 이중 색조 조명. 현대 뮤직비디오/드라마 미학.","visual_effect_ko":"이중성, 현대적 세련미, 대비적 아름다움","best_for":["music_video","character_duality","modern_drama"],"prompt_keywords":{"kling":"bisexual lighting, pink and blue neon lights from opposite sides, dual-tone face lighting","seedance":"dual-tone bisexual lighting, magenta from left and cyan from right, split face illumination","veo":"Close-up on 85mm lens: bisexual lighting with hot pink from left and cool blue from right, split-face dual-tone, contemporary editorial aesthetic"},"combinable_with":["neon_saturated","extreme_closeup","symmetric_composition"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"rembrandt_lighting","category":"lighting","name_ko":"렘브란트 라이팅","name_en":"Rembrandt Lighting","description_ko":"코 그림자가 반대쪽 볼의 삼각형 하이라이트를 만드는 클래식 초상화 조명.","visual_effect_ko":"고전적 깊이, 인물의 입체감, 회화적 아름다움","best_for":["portrait","drama","character_study"],"prompt_keywords":{"kling":"Rembrandt lighting, triangle highlight on shadowed cheek, classic portrait lighting setup","seedance":"Rembrandt portrait lighting, nose shadow meeting cheek shadow to form triangle, warm key with dramatic fill ratio","veo":"Close-up on 85mm lens: Rembrandt lighting with triangle highlight on shadowed cheek, warm key light at 45 degrees, deep shadow sculpting, painterly portrait quality"},"combinable_with":["chiaroscuro","rule_of_thirds","slow_push_in"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"underlight","category":"lighting","name_ko":"언더라이트","name_en":"Underlight","description_ko":"아래에서 위로 비추는 조명. 공포, 초자연, 위협적 분위기 연출.","visual_effect_ko":"공포감, 초자연적 불안, 위협적 변형","best_for":["horror","villain","supernatural"],"prompt_keywords":{"kling":"underlight from below, upward casting harsh shadows on face, horror campfire lighting","seedance":"sinister underlight casting upward shadows, face illuminated from below, distorted frightening shadow patterns","veo":"Close-up on 50mm lens: harsh underlight from below casting distorted upward shadows on face, horror campfire effect, supernatural unease, inverted shadow pattern"},"combinable_with":["low_key_lighting","extreme_closeup","slow_push_in"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    {"technique_id":"dappled_light","category":"lighting","name_ko":"나뭇잎 산광","name_en":"Dappled Light","description_ko":"나뭇잎이나 격자 사이로 떨어지는 얼룩무늬 빛. 유기적 자연광 텍스처.","visual_effect_ko":"자연스러운 아름다움, 유기적 텍스처, 평화로운 분위기","best_for":["romance","nature","peaceful_moment"],"prompt_keywords":{"kling":"dappled light through leaves, sun-spotted shadows on subject, natural foliage pattern lighting","seedance":"dappled sunlight filtering through canopy, irregular leaf-shadow patterns dancing on subject, organic natural illumination","veo":"Medium shot on 50mm lens: dappled sunlight filtering through tree canopy, dancing leaf-shadow patterns on subject, organic warm natural lighting, peaceful ethereal atmosphere"},"combinable_with":["natural_golden_hour","soft_diffused_light","lateral_tracking"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"practical_light_only","category":"lighting","name_ko":"프랙티컬 라이트 온리","name_en":"Practical Light Only","description_ko":"씬 내 실제 광원(램프, 촛불, 모니터)만으로 조명. 극사실적 분위기.","visual_effect_ko":"극사실성, 현장감, 자연스러운 생활감","best_for":["realism","intimate_scene","documentary"],"prompt_keywords":{"kling":"practical lighting only, illuminated by in-scene lamps and candles, no artificial film lights","seedance":"practical light sources only, room lit by table lamp and window, authentic lived-in illumination quality","veo":"Medium shot on 35mm lens: lit only by practical sources, warm table lamp and cool window light mixing, authentic lived-in quality, no artificial film lighting, documentary realism"},"combinable_with":["eye_level","long_take","warm_desaturated"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    # === color (new additions) ===
    {"technique_id":"bleach_bypass","category":"color","name_ko":"블리치 바이패스","name_en":"Bleach Bypass","description_ko":"은 보존 처리로 채도를 낮추고 콘트라스트를 높인 그레이딩. 전쟁/스릴러에 자주 사용.","visual_effect_ko":"거칠고 건조한 질감, 높은 콘트라스트, 탈색된 현실","best_for":["war","thriller","gritty_realism"],"prompt_keywords":{"kling":"bleach bypass look, desaturated high contrast, silver retained film processing","seedance":"bleach bypass color grading, muted desaturated colors with crushed blacks, harsh metallic contrast","veo":"Medium shot on 35mm lens: bleach bypass grading with desaturated palette, high contrast crushed blacks, silver-retained harsh texture, gritty war documentary feel"},"combinable_with":["hard_contrast_light","handheld_shaky","desaturated_muted"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"teal_orange_grade","category":"color","name_ko":"틸/오렌지 그레이딩","name_en":"Teal and Orange Grade","description_ko":"보색 대비의 블록버스터 표준 컬러 그레이딩. 피부톤(오렌지) vs 배경(틸).","visual_effect_ko":"블록버스터 세련미, 인물 분리, 영화적 광택","best_for":["blockbuster","action","commercial"],"prompt_keywords":{"kling":"teal and orange color grading, warm skin tones against cool blue-green backgrounds","seedance":"Hollywood teal-orange grading, complementary warm skin against cool teal shadows, blockbuster color science","veo":"Medium shot on 50mm lens: teal and orange color grading, warm orange skin tones separated from cool teal backgrounds, blockbuster color science, polished cinematic look"},"combinable_with":["complementary_contrast","dolly_in","rim_light"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"sepia_tone","category":"color","name_ko":"세피아 톤","name_en":"Sepia Tone","description_ko":"갈색 톤의 빈티지 컬러 처리. 과거 회상, 오래된 사진, 향수 연출.","visual_effect_ko":"시간의 경과, 옛 기억, 따뜻한 빈티지","best_for":["flashback","nostalgia","period_piece"],"prompt_keywords":{"kling":"sepia tone, warm brown vintage color treatment, aged photograph look","seedance":"sepia-toned vintage warmth, brown monochrome aged appearance, faded historical photograph quality","veo":"Medium shot on 50mm lens: sepia-toned vintage look, warm brown monochrome, faded edges, aged historical photograph quality, nostalgic time-passed atmosphere"},"combinable_with":["warm_desaturated","slow_dissolve","film_grain_vintage"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"day_for_night","category":"color","name_ko":"데이 포 나이트","name_en":"Day for Night","description_ko":"낮에 촬영하여 밤처럼 보이게 하는 그레이딩. 블루 톤 + 노출 다운.","visual_effect_ko":"인위적 야경, 신비로운 달빛, 레트로 영화 기법","best_for":["night_scene","retro","budget_filmmaking"],"prompt_keywords":{"kling":"day for night look, heavy blue tint simulating moonlight, underexposed daytime footage","seedance":"day-for-night grading, deep blue moonlight simulation, artificially darkened daytime with visible sky detail","veo":"Wide shot on 35mm lens: day-for-night grading, deep blue moonlight tint over daytime footage, underexposed with visible sky detail, classic Hollywood night simulation"},"combinable_with":["cool_blue","silhouette","high_angle"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    # === editing_rhythm (new additions) ===
    {"technique_id":"speed_ramp","category":"editing_rhythm","name_ko":"스피드 램프","name_en":"Speed Ramp","description_ko":"속도를 점진적으로 변환(슬로모→정상 또는 반대). 액션의 하이라이트 강조.","visual_effect_ko":"시간 조작, 액션 강조, 리듬 변주","best_for":["action_highlight","sports","dramatic_moment"],"prompt_keywords":{"kling":"speed ramp from slow motion to real-time, time manipulation acceleration","seedance":"speed ramping from slow-motion to normal speed, dynamic temporal shift emphasizing peak action","veo":"Medium shot on 50mm lens: speed ramp transitioning from slow-motion to real-time at action peak, temporal acceleration, dramatic timing emphasis"},"combinable_with":["crash_zoom","arc_orbit","whip_pan"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    {"technique_id":"reverse_motion","category":"editing_rhythm","name_ko":"리버스 모션","name_en":"Reverse Motion","description_ko":"시간 역행 촬영. 파괴의 복원, 초현실적 효과, 되감기 미학.","visual_effect_ko":"시간 역전, 초현실, 수복의 상징","best_for":["surreal","music_video","metaphor"],"prompt_keywords":{"kling":"reverse motion playback, time flowing backwards, objects reassembling","seedance":"reverse playback motion, shattered pieces reassembling, time-reversed action with supernatural quality","veo":"Medium shot on 35mm lens: reverse motion with objects reassembling, liquid flowing upward, time rewinding, supernatural restoration, surreal temporal reversal"},"combinable_with":["slow_motion_editing","cross_dissolve","dutch_angle"],"source_refs":["web_research_2026"],"multi_shot_hint":"closer"},
    {"technique_id":"freeze_frame","category":"editing_rhythm","name_ko":"프리즈 프레임","name_en":"Freeze Frame","description_ko":"특정 순간에서 영상을 정지. 강조, 내레이션, 극적 중단 효과.","visual_effect_ko":"시간 정지, 극적 강조, 서사적 개입","best_for":["narration","character_intro","ending"],"prompt_keywords":{"kling":"freeze frame hold, action paused at peak moment, still frame dramatic emphasis","seedance":"freeze frame at dramatic peak, motion halting completely, time-stop emphasis with narrative weight","veo":"Medium shot on 50mm lens: freeze frame at peak action moment, complete motion stop, dramatic narrative emphasis, time-frozen stillness"},"combinable_with":["crash_zoom","arc_orbit","slow_motion_editing"],"source_refs":["web_research_2026"],"multi_shot_hint":"closer"},
    # === composition (new additions) ===
    {"technique_id":"center_framing","category":"composition","name_ko":"센터 프레이밍","name_en":"Center Framing","description_ko":"피사체를 정확히 프레임 중앙에 배치. 직관적 집중, 대칭 미학, 웨스 앤더슨 스타일.","visual_effect_ko":"즉각적 주의집중, 의도적 정면성, 정적 권위","best_for":["character_focus","comedy","confrontation"],"prompt_keywords":{"kling":"center framed subject, dead-center positioning, direct frontal symmetry","seedance":"perfectly center-framed subject, dead-center placement, front-facing direct address composition","veo":"Medium shot on 50mm lens: subject perfectly centered in frame, dead-center direct address, flat frontal symmetry, intentional graphic precision"},"combinable_with":["symmetric_composition","eye_level","high_key_lighting"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"power_position","category":"composition","name_ko":"파워 포지션","name_en":"Power Position","description_ko":"인물을 프레임 상단 1/3에 배치하여 지배력, 권위감 표현.","visual_effect_ko":"지배력, 권위, 위압적 존재감","best_for":["villain","leader","authority"],"prompt_keywords":{"kling":"power position framing, subject occupying upper third of frame, dominant positioning","seedance":"power-positioned subject in upper frame, dominant headroom-free framing, authoritative visual placement","veo":"Low angle on 35mm lens: subject positioned in upper third of frame, power-dominant placement, minimal headroom, authoritative commanding presence"},"combinable_with":["low_angle","hard_contrast_light","symmetric_composition"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"tight_framing","category":"composition","name_ko":"타이트 프레이밍","name_en":"Tight Framing","description_ko":"피사체 주변 여백을 최소화한 압박적 프레이밍. 폐소공포, 긴장, 집중.","visual_effect_ko":"압박감, 폐소공포, 탈출 불가의 긴장","best_for":["tension","claustrophobia","interrogation"],"prompt_keywords":{"kling":"tight framing with minimal headroom, claustrophobic close composition, compressed space","seedance":"oppressively tight framing, subject filling frame with no breathing room, claustrophobic compression","veo":"Close-up on 85mm lens: extremely tight framing with minimal headroom and side room, claustrophobic compression, no visual escape, oppressive closeness"},"combinable_with":["extreme_closeup","slow_push_in","hard_contrast_light"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    # === transition (new additions) ===
    {"technique_id":"iris_transition","category":"transition","name_ko":"아이리스 전환","name_en":"Iris Transition","description_ko":"원형으로 열리거나 닫히는 전환. 무성영화/레트로/만화적 효과.","visual_effect_ko":"레트로 스타일, 만화적 강조, 고전적 마무리","best_for":["retro","comedy","ending"],"prompt_keywords":{"kling":"iris wipe transition, circular opening or closing, classic silent film transition","seedance":"iris wipe transition, circular aperture opening or closing to black, vintage silent-era punctuation","veo":"Iris wipe transition: circular aperture closing to black centered on subject, classic silent-film ending, retro punctuation mark"},"combinable_with":["center_framing","sepia_tone","freeze_frame"],"source_refs":["web_research_2026"],"multi_shot_hint":"closer"},
    {"technique_id":"morph_transition","category":"transition","name_ko":"모프 전환","name_en":"Morph Transition","description_ko":"한 이미지가 다른 이미지로 유기적으로 변형되는 전환. AI 네이티브 기법.","visual_effect_ko":"유기적 변형, 매끄러운 연결, 초현실적 플로우","best_for":["music_video","dream","transformation"],"prompt_keywords":{"kling":"morph transition, one form organically transforming into another, seamless shape-shift","seedance":"smooth morph transition, subject organically shape-shifting into next form, fluid metamorphosis between scenes","veo":"Morph transition: subject smoothly transforming shape into next scene's subject, organic fluid metamorphosis, seamless AI-native morphing between forms"},"combinable_with":["slow_dissolve","cross_dissolve","slow_motion_editing"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    # === focus_technique (new additions) ===  
    {"technique_id":"split_diopter","category":"focus_technique","name_ko":"스플릿 디옵터","name_en":"Split Diopter","description_ko":"특수 렌즈 필터로 전경과 배경 모두 동시 포커스. 이중 서사, 긴장의 공존.","visual_effect_ko":"이중 초점, 병렬 서사, 불안한 공존","best_for":["dual_narrative","tension","confrontation"],"prompt_keywords":{"kling":"split diopter effect, both foreground and background simultaneously in sharp focus, dual-focus tension","seedance":"split diopter dual focus, foreground and background equally sharp, bifocal tension composition","veo":"Medium shot with split diopter: foreground subject and background element both in razor-sharp focus simultaneously, dual-narrative tension, unsettling bifocal clarity"},"combinable_with":["frame_within_frame","chiaroscuro","over_the_shoulder"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    {"technique_id":"tilt_shift_focus","category":"focus_technique","name_ko":"틸트 시프트 포커스","name_en":"Tilt-Shift Focus","description_ko":"렌즈 틸트로 초점면 기울임. 미니어처 효과, 선택적 블러, 위에서 내려다보는 도시.","visual_effect_ko":"미니어처 효과, 장난감 세계, 초현실적 스케일","best_for":["establishing_shot","whimsy","abstract"],"prompt_keywords":{"kling":"tilt-shift miniature effect, selective focus band making scene look toy-like","seedance":"tilt-shift miniature focus, real scene appearing as tiny model, extreme selective blur bands","veo":"Bird's-eye shot with tilt-shift lens: miniature effect making real cityscape look like toy model, narrow selective focus band, surreal scale distortion"},"combinable_with":["bird_eye","high_angle","pastel_palette"],"source_refs":["web_research_2026"],"multi_shot_hint":"opener"},
    # === physics_motion (NEW CATEGORY) ===
    {"technique_id":"cloth_simulation","category":"physics_motion","name_ko":"천 시뮬레이션","name_en":"Cloth Simulation","description_ko":"직물, 의상, 커튼 등의 물리적 움직임을 정밀하게 재현. Veo 3.1 물리 엔진 활용.","visual_effect_ko":"질감의 사실감, 물리적 존재감, 유기적 흐름","best_for":["fashion","action","wind_scene"],"prompt_keywords":{"kling":"realistic cloth physics, fabric draping and flowing with wind, garment weight and inertia","seedance":"physically accurate cloth movement, fabric billowing and settling with weight, textile physics simulation","veo":"Medium shot on 50mm lens: cloth simulation with fabric reacting to wind and gravity, realistic draping and billowing, material weight and inertia visible, silk flow physics"},"combinable_with":["lateral_tracking","soft_diffused_light","slow_motion_editing"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"liquid_dynamics","category":"physics_motion","name_ko":"액체 다이나믹스","name_en":"Liquid Dynamics","description_ko":"물, 잉크, 페인트 등 액체의 물리적 움직임. 스플래시, 리플, 푸어링.","visual_effect_ko":"유동적 아름다움, 물리적 역동성, 시각적 충격","best_for":["product_shot","abstract","high_speed"],"prompt_keywords":{"kling":"liquid dynamics, water splashing with realistic physics, fluid pouring and rippling","seedance":"physically accurate liquid motion, water splash with droplets and surface tension, fluid dynamics simulation","veo":"Close-up on 100mm macro lens: liquid dynamics with splash physics, droplets separating with surface tension, fluid motion captured in precise detail, hydrodynamic realism"},"combinable_with":["slow_motion_editing","crash_zoom","high_key_lighting"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    {"technique_id":"particle_dispersion","category":"physics_motion","name_ko":"파티클 디스퍼전","name_en":"Particle Dispersion","description_ko":"먼지, 연기, 불꽃, 꽃잎 등 입자의 물리적 확산. 대기감과 시각적 질감 추가.","visual_effect_ko":"대기감, 시각적 질감, 공간의 깊이","best_for":["atmosphere","action_aftermath","beauty_shot"],"prompt_keywords":{"kling":"particle dispersion, dust motes floating in light beam, smoke wisps curling","seedance":"atmospheric particle effects, floating dust illuminated by light shaft, organic debris dispersion","veo":"Medium shot on 50mm lens: particle dispersion with dust motes floating through light beam, smoke wisps curling with air currents, atmospheric depth and texture"},"combinable_with":["rim_light","chiaroscuro","slow_motion_editing"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"hair_physics","category":"physics_motion","name_ko":"헤어 물리","name_en":"Hair Physics","description_ko":"머리카락의 물리적 움직임. 바람, 회전, 관성에 따른 자연스러운 모발 역학.","visual_effect_ko":"캐릭터 사실감, 유기적 움직임, 감각적 디테일","best_for":["character_shot","beauty","slow_motion"],"prompt_keywords":{"kling":"realistic hair physics, strands flowing and bouncing with movement, wind-blown hair dynamics","seedance":"physically accurate hair movement, individual strands reacting to wind and motion, natural hair sway and bounce","veo":"Close-up on 85mm lens: hair physics with individual strands flowing in wind, natural sway bounce and settle, realistic hair dynamics with weight and inertia"},"combinable_with":["slow_motion_editing","rim_light","soft_diffused_light"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    # === shot_scale (new additions) ===
    {"technique_id":"establishing_shot","category":"shot_scale","name_ko":"이스타블리싱 샷","name_en":"Establishing Shot","description_ko":"장소와 시간을 소개하는 와이드 샷. 씬 진입의 맥락 설정.","visual_effect_ko":"공간 소개, 맥락 설정, 서사 진입","best_for":["scene_opening","location_intro","time_setting"],"prompt_keywords":{"kling":"establishing wide shot showing full location and time of day, contextual scene introduction","seedance":"cinematic establishing shot revealing complete environment, wide location overview setting narrative context","veo":"Extreme wide establishing shot on 16mm lens: full location reveal with time-of-day context, architectural or natural environment overview, narrative scene-setting"},"combinable_with":["crane_down","natural_golden_hour","deep_focus"],"source_refs":["web_research_2026"],"multi_shot_hint":"opener"},
    {"technique_id":"two_shot","category":"shot_scale","name_ko":"투 샷","name_en":"Two Shot","description_ko":"두 인물을 동시에 프레임에 담는 샷. 대화, 관계, 대립 연출.","visual_effect_ko":"관계 역학, 상호작용, 병렬적 존재","best_for":["dialogue","relationship","confrontation"],"prompt_keywords":{"kling":"two shot framing both characters, dual subject composition, paired character framing","seedance":"two-shot composition with both characters equally framed, relational spatial dynamic, dual subject dialogue setup","veo":"Medium two-shot on 35mm lens: both characters equally framed in conversation position, relational spatial dynamic, balanced dual-subject composition"},"combinable_with":["eye_level","rule_of_thirds","soft_diffused_light"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    # === camera_angle (new additions) ===
    {"technique_id":"gods_eye_view","category":"camera_angle","name_ko":"갓즈 아이 뷰","name_en":"God's Eye View","description_ko":"인물을 정확히 위에서 수직으로 내려다보는 극단적 하이앵글. 운명, 통제, 무력감.","visual_effect_ko":"전지적 관찰, 운명적 시점, 미시적 패턴","best_for":["fate","surveillance","pattern"],"prompt_keywords":{"kling":"god's eye view, camera directly above looking straight down at subject, extreme overhead vertical","seedance":"god's-eye vertical overhead, subject viewed from directly above, fate-like omniscient perspective","veo":"God's-eye shot on 24mm lens: camera positioned directly above looking straight down, subject flattened into graphic pattern, omniscient fate-like perspective, extreme vertical overhead"},"combinable_with":["bird_eye","negative_space","slow_dissolve"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"canted_pov","category":"camera_angle","name_ko":"감정적 POV","name_en":"Canted POV","description_ko":"캐릭터 시점 + 기울어진 프레임. 취한/다친/혼란 상태의 주관적 시점.","visual_effect_ko":"주관적 혼란, 캐릭터 내면, 불안정한 인식","best_for":["drunk_scene","injury","confusion"],"prompt_keywords":{"kling":"canted POV shot, tilted first-person perspective, disoriented subjective viewpoint","seedance":"canted point-of-view, tilted subjective perspective simulating disorientation, character's unsteady personal vision","veo":"Canted POV on 24mm lens: tilted first-person perspective, swaying unsteady movement, blurred edges, disoriented subjective viewpoint simulating impaired state"},"combinable_with":["dutch_angle","handheld_shaky","lens_whacking"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    # === additional lighting ===
    {"technique_id":"motivated_lighting","category":"lighting","name_ko":"모티베이티드 라이팅","name_en":"Motivated Lighting","description_ko":"씬 내 광원(창문, 램프, TV)에 의해 동기 부여된 조명 설정. 현실적 빛 방향성.","visual_effect_ko":"사실적 광원, 논리적 조명, 몰입적 공간감","best_for":["realism","interior","drama"],"prompt_keywords":{"kling":"motivated lighting from visible window source, light direction matching practical sources in scene","seedance":"motivated lighting with visible source justification, window-light direction matching scene geography, realistic illumination logic","veo":"Medium shot on 35mm lens: motivated lighting justified by visible window, light direction and color temperature matching practical source, realistic spatial illumination logic"},"combinable_with":["practical_light_only","soft_diffused_light","rule_of_thirds"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"bounce_light","category":"lighting","name_ko":"바운스 라이트","name_en":"Bounce Light","description_ko":"벽, 천장, 반사판 등에서 반사된 부드러운 간접광. 자연스럽고 부드러운 조명.","visual_effect_ko":"부드러운 확산, 자연스러운 필, 그림자 완화","best_for":["beauty","interview","soft_scene"],"prompt_keywords":{"kling":"bounced soft light, indirect illumination reflected off walls, gentle wrapping fill","seedance":"soft bounced indirect lighting, warm wall-reflected fill, gentle shadow-softening reflected illumination","veo":"Medium shot on 50mm lens: soft bounced light reflected off warm walls, gentle wrapping indirect illumination, minimal harsh shadows, naturally soft beauty lighting"},"combinable_with":["soft_diffused_light","eye_level","rule_of_thirds"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    # === additional editing_rhythm ===
    {"technique_id":"smash_cut","category":"editing_rhythm","name_ko":"스매시 컷","name_en":"Smash Cut","description_ko":"갑작스러운 직접 전환으로 극적 대비 생성. 꿈→현실, 평화→혼란.","visual_effect_ko":"극적 대비, 충격적 전환, 서사적 단절","best_for":["dream_to_reality","comedic_contrast","shock"],"prompt_keywords":{"kling":"smash cut, abrupt jarring transition between contrasting scenes, no transition buffer","seedance":"smash cut with zero transition, abrupt jump between contrasting tones, jarring immediate scene change","veo":"Smash cut: abrupt zero-transition jump from peaceful to chaotic scene, jarring tonal contrast, no dissolve or fade, immediate dramatic shift"},"combinable_with":["crash_zoom","rapid_cuts","flash_cut"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    # === additional composition ===
    {"technique_id":"visual_rhyme","category":"composition","name_ko":"비주얼 라임","name_en":"Visual Rhyme","description_ko":"다른 씬에서 유사한 형태/구도를 반복하여 시각적 연결성 생성.","visual_effect_ko":"시각적 연결, 테마적 반복, 은유적 대응","best_for":["parallel_narrative","thematic_connection","montage"],"prompt_keywords":{"kling":"visual rhyme, matching compositional element echoing previous scene's shape or framing","seedance":"visual rhyme composition, recurring shape or framing pattern connecting thematically to earlier scene","veo":"Medium shot on 50mm lens: visual rhyme echoing earlier scene's composition, matching shape language and framing, thematic visual callback, narrative symmetry"},"combinable_with":["match_cut","rule_of_thirds","cross_dissolve"],"source_refs":["web_research_2026"],"multi_shot_hint":"closer"},
    # === additional camera_movement ===
    {"technique_id":"rotation_360","category":"camera_movement","name_ko":"360도 회전","name_en":"360 Rotation","description_ko":"카메라가 피사체를 완전히 360도 회전. 시간 경과, 변신, 에너지 폭발.","visual_effect_ko":"완전한 순환, 시간의 흐름, 에너지 폭발","best_for":["transformation","time_passage","energy_peak"],"prompt_keywords":{"kling":"360 degree camera rotation around subject, full orbital revolution, complete circular tracking","seedance":"full 360-degree revolution around subject, complete circular orbit, continuous rotational tracking","veo":"Full 360-degree orbit on 35mm lens: camera completing full revolution around subject, continuous rotational tracking, transformative circular motion, energy peak emphasis"},"combinable_with":["arc_orbit","speed_ramp","rim_light"],"source_refs":["web_research_2026"],"multi_shot_hint":"middle"},
    # === additional lens_character ===
    {"technique_id":"vintage_lens","category":"lens_character","name_ko":"빈티지 렌즈","name_en":"Vintage Lens Character","description_ko":"올드 렌즈 특유의 부드러운 글로우, 색수차, 불완전한 보케. 아날로그 질감.","visual_effect_ko":"아날로그 따뜻함, 불완전한 아름다움, 시대적 질감","best_for":["period_piece","nostalgia","indie"],"prompt_keywords":{"kling":"vintage lens character, soft glow haze, chromatic aberration, imperfect organic bokeh","seedance":"vintage lens rendering, soft glowing highlights with subtle chromatic fringing, analog imperfection warmth","veo":"Medium shot on vintage 50mm lens: soft highlight glow with chromatic aberration, imperfect organic bokeh, analog warmth and character, nostalgic lens imperfection"},"combinable_with":["warm_desaturated","natural_golden_hour","film_grain_vintage"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
    {"technique_id":"film_grain_vintage","category":"lens_character","name_ko":"빈티지 필름 그레인","name_en":"Vintage Film Grain","description_ko":"35mm/16mm 필름 구조의 유기적 그레인 텍스처. 아날로그 시대의 질감.","visual_effect_ko":"아날로그 질감, 유기적 텍스처, 시대적 진정성","best_for":["period_piece","nostalgia","documentary"],"prompt_keywords":{"kling":"vintage film grain texture, organic analog noise pattern, 35mm celluloid grain structure","seedance":"organic film grain texture, authentic 35mm celluloid noise, analog photochemical grain character","veo":"Shot on 35mm film stock: organic photochemical grain texture, analog noise character, authentic celluloid quality, visible film weave and gate flicker"},"combinable_with":["warm_desaturated","sepia_tone","vintage_lens"],"source_refs":["web_research_2026"],"multi_shot_hint":"any"},
]

with open(CORPUS_PATH, 'r') as f:
    corpus = json.load(f)

# 1) Add new techniques
existing_ids = {t["technique_id"] for t in corpus["techniques"]}
added = 0
for t in NEW_TECHNIQUES:
    if t["technique_id"] not in existing_ids:
        corpus["techniques"].append(t)
        existing_ids.add(t["technique_id"])
        added += 1

# 2) Update mood_technique_map with new techniques
new_mood_entries = {
    "tension": ["vertigo_effect", "split_diopter", "tight_framing"],
    "chaos": ["crash_zoom", "fpv_drone_dive", "rotation_360"],
    "nostalgia": ["sepia_tone", "vintage_lens", "film_grain_vintage"],
    "surreal": ["lens_whacking", "morph_transition", "parallax_scroll"],
    "energy": ["speed_ramp", "crash_zoom", "fpv_drone_dive"],
    "dread": ["underlight", "canted_pov", "vertigo_effect"],
    "whimsy": ["iris_transition", "wes_anderson_flat", "tilt_shift_focus"],
    "joy": ["dappled_light", "bounce_light"],
    "awe": ["fpv_drone_dive", "gods_eye_view"],
    "triumph": ["speed_ramp", "freeze_frame"],
}
for mood, techs in new_mood_entries.items():
    if mood in corpus["mood_technique_map"]:
        existing = set(corpus["mood_technique_map"][mood])
        for t in techs:
            if t not in existing:
                corpus["mood_technique_map"][mood].append(t)

# 3) Update metadata
categories = {}
for t in corpus["techniques"]:
    cat = t["category"]
    categories[cat] = categories.get(cat, 0) + 1

corpus["metadata"]["total_techniques"] = len(corpus["techniques"])
corpus["metadata"]["categories"] = dict(sorted(categories.items()))

# 4) Write back
with open(CORPUS_PATH, 'w') as f:
    json.dump(corpus, f, indent=2, ensure_ascii=False)

print(f"Added {added} new techniques")
print(f"Total techniques: {len(corpus['techniques'])}")
print(f"Categories: {json.dumps(categories, indent=2)}")
