"""
VDG Unified Pass Schema Definitions

Schemas for the 2-Pass Unified Pipeline:
- Pass 1: UnifiedPass (LLM semantic + audio/motion context)
- Pass 2: CVMeasurementPass (deterministic CV measurement)

These extend vdg_v4.py with additional types needed for
the unified pipeline architecture.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

from pydantic import BaseModel, Field


# =============================================================================
# Enums
# =============================================================================


class AnalysisPriority(str, Enum):
    """Priority levels for analysis points."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class MeasurementMethod(str, Enum):
    """Measurement method for metrics."""
    LLM = "llm"
    CV = "cv"
    HYBRID = "hybrid"


class MovementType(str, Enum):
    """Types of camera/subject movement."""
    STATIC = "static"
    PAN_LEFT = "pan_left"
    PAN_RIGHT = "pan_right"
    TILT_UP = "tilt_up"
    TILT_DOWN = "tilt_down"
    ZOOM_IN = "zoom_in"
    ZOOM_OUT = "zoom_out"
    DOLLY_IN = "dolly_in"
    DOLLY_OUT = "dolly_out"
    TRACKING = "tracking"
    HANDHELD = "handheld"
    CRANE = "crane"
    MIXED = "mixed"


# =============================================================================
# Analysis Point Seed (Pass 1 → Pass 2)
# =============================================================================


class MeasurementSpecLLM(BaseModel):
    """LLM-generated measurement specification for CV pass."""
    metric_id: str = Field(description="Metric ID (e.g., 'center_offset', 'brightness', 'blur')")
    measurement_method: MeasurementMethod = Field(default=MeasurementMethod.CV)
    priority: AnalysisPriority = Field(default=AnalysisPriority.MEDIUM)
    target_entity_key: Optional[str] = Field(default=None, description="Entity key to measure")
    notes: Optional[str] = Field(default=None, description="Additional measurement instructions")


class AnalysisPointSeedLLM(BaseModel):
    """
    Single analysis point seed from Pass 1.

    Used to guide CV measurement in Pass 2.
    """
    t_center_ms: int = Field(description="Center timestamp in milliseconds")
    t_window_ms: int = Field(default=1000, description="Window size in milliseconds (default 1s)")
    priority: str = Field(default="medium", description="critical/high/medium/low")
    reason: str = Field(description="Why this point is interesting")
    target_entity_keys: List[str] = Field(default_factory=list, description="Entity keys to track")
    measurement_specs: List[MeasurementSpecLLM] = Field(default_factory=list)
    evidence_note: Optional[str] = Field(default=None, description="Evidence observation")

    @property
    def t_window(self) -> Tuple[int, int]:
        """Get time window as (start_ms, end_ms)."""
        half = self.t_window_ms // 2
        return (self.t_center_ms - half, self.t_center_ms + half)


class AnalysisPlanLLM(BaseModel):
    """
    Analysis plan generated by UnifiedPass (Pass 1).

    Contains all analysis points with measurement specifications
    for the CV pass.
    """
    points: List[AnalysisPointSeedLLM] = Field(default_factory=list)
    total_points: int = Field(default=0)
    coverage_ms: int = Field(default=0, description="Total video time covered")
    sampling_fps: float = Field(default=10.0, description="Recommended sampling FPS for CV")


# =============================================================================
# Entity Hints (Pass 1 → Pass 2)
# =============================================================================


class EntityHintLLM(BaseModel):
    """Entity hint from Pass 1 for CV tracking in Pass 2."""
    key: str = Field(description="Stable entity key (e.g., 'main_person', 'product_a')")
    entity_type: str = Field(description="'person', 'object', 'text', 'scene'")
    description: str = Field(description="Visual description for CV detection")
    first_seen_ms: Optional[int] = Field(default=None)
    last_seen_ms: Optional[int] = Field(default=None)
    bounding_box_hint: Optional[Dict[str, float]] = Field(
        default=None,
        description="Approximate bbox {x, y, w, h} normalized 0-1"
    )


# =============================================================================
# Hook Attributes (3-Axis Classification)
# =============================================================================


class HookAttributesLLM(BaseModel):
    """3-axis hook classification from LLM analysis."""
    format: str = Field(default="unknown", description="pov/skit/listicle/tutorial/challenge/duet/vlog/meme_remix/reaction/storytime/unknown")
    trigger: str = Field(default="unknown", description="curiosity_gap/shock/relatability/satisfaction/educational/humor/nostalgia/fear/aspiration/unknown")
    device: str = Field(default="unknown", description="text_on_screen/visual_hook/loud_noise/question/countdown/insert_clip/direct_address/cliffhanger/misdirection/unknown")
    secondary_triggers: List[str] = Field(default_factory=list, description="Additional triggers")
    format_confidence: float = Field(default=0.7, ge=0.0, le=1.0)
    trigger_confidence: float = Field(default=0.7, ge=0.0, le=1.0)
    device_confidence: float = Field(default=0.7, ge=0.0, le=1.0)
    classification_reasoning: Optional[str] = Field(default=None, description="Brief explanation")


# =============================================================================
# Hook Genome (Pass 1)
# =============================================================================


class MicrobeatLLM(BaseModel):
    """Single microbeat in hook structure."""
    beat_id: str = Field(description="e.g., 'beat_001'")
    t_start_ms: int
    t_end_ms: int
    role: str = Field(description="'attention_grab', 'context_set', 'hook_trigger', 'promise'")
    description: str = Field(default="")
    visual_element: Optional[str] = Field(default=None)
    audio_element: Optional[str] = Field(default=None)


class HookGenomeLLM(BaseModel):
    """Hook genome extracted by Pass 1."""
    pattern: str = Field(description="Hook pattern type")
    strength: float = Field(ge=0.0, le=1.0, description="Hook effectiveness 0-1")
    microbeats: List[MicrobeatLLM] = Field(default_factory=list)
    trigger_element: Optional[str] = Field(default=None)
    emotional_target: Optional[str] = Field(default=None)
    audio_sync_score: Optional[float] = Field(
        default=None,
        ge=0.0, le=1.0,
        description="How well hook syncs with audio beats"
    )
    hook_attributes: Optional[HookAttributesLLM] = Field(
        default=None,
        description="3-axis classification (format, trigger, device)"
    )


# =============================================================================
# Scene (Pass 1)
# =============================================================================


class SceneLLM(BaseModel):
    """Scene extracted by Pass 1."""
    scene_id: str
    t_start_ms: int
    t_end_ms: int
    role: str = Field(description="'hook', 'setup', 'development', 'climax', 'resolution', 'cta'")
    description: str = Field(default="")
    key_elements: List[str] = Field(default_factory=list)
    dominant_movement: Optional[str] = Field(default=None, description="Camera movement type")


# =============================================================================
# Capsule Brief (Pass 1)
# =============================================================================


class CapsuleBriefLLM(BaseModel):
    """High-level brief extracted by Pass 1."""
    dos: List[str] = Field(default_factory=list, description="Techniques to replicate")
    donts: List[str] = Field(default_factory=list, description="Things to avoid")
    key_insight: Optional[str] = Field(default=None)
    shotlist_summary: Optional[str] = Field(default=None, description="Quick shot breakdown")


# =============================================================================
# Unified Pass LLM Output (Pass 1 Result)
# =============================================================================


class UnifiedPassLLMOutput(BaseModel):
    """
    Complete output from UnifiedPass (Pass 1).

    Combines semantic analysis with audio/motion context
    to produce a comprehensive analysis plan for CV pass.
    """
    # Hook Analysis
    hook_genome: Optional[HookGenomeLLM] = Field(default=None)

    # Scene Structure
    scenes: List[SceneLLM] = Field(default_factory=list)

    # Entity Hints for CV Tracking
    entity_hints: List[EntityHintLLM] = Field(default_factory=list)

    # Analysis Plan for Pass 2
    analysis_plan: AnalysisPlanLLM = Field(default_factory=AnalysisPlanLLM)

    # Mise-en-scene Signals (from comments)
    mise_en_scene_signals: List[Dict[str, Any]] = Field(default_factory=list)

    # Brief
    capsule_brief: Optional[CapsuleBriefLLM] = Field(default=None)

    # Narrative Summary
    narrative_summary: Optional[str] = Field(default=None)

    # Audio/Motion Context Integration
    audio_context_used: bool = Field(default=False, description="Was audio analysis integrated")
    motion_context_used: bool = Field(default=False, description="Was motion analysis integrated")

    # Comment Evidence (top 5 relevant comments)
    comment_evidence_top5: List[Dict[str, Any]] = Field(default_factory=list)


# =============================================================================
# CV Measurement Types (Pass 2)
# =============================================================================


@dataclass
class MetricResult:
    """Result of a single CV metric measurement."""
    metric_id: str
    value: Any = None
    unit: Optional[str] = None
    confidence: float = 1.0
    t_ms: Optional[int] = None
    samples: List[Any] = field(default_factory=list)
    missing_reason: Optional[str] = None


@dataclass
class PointMeasurement:
    """CV measurements for a single analysis point."""
    t_center_ms: int
    t_window_ms: int
    metrics: Dict[str, MetricResult] = field(default_factory=dict)
    evidence_frame_path: Optional[str] = None
    frames_analyzed: int = 0


@dataclass
class CVMeasurementResult:
    """Complete result from CV Measurement Pass."""
    measurements: List[PointMeasurement] = field(default_factory=list)
    total_frames_processed: int = 0
    processing_time_ms: int = 0
    errors: List[str] = field(default_factory=list)


@dataclass
class CVPassProvenance:
    """Provenance tracking for CV pass."""
    extraction_fps: float = 10.0
    opencv_version: str = ""
    ffmpeg_version: str = ""
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    frames_extracted: int = 0
    metrics_computed: int = 0


# =============================================================================
# Motion Analysis Types
# =============================================================================


@dataclass
class MotionSegment:
    """Motion segment detected in video."""
    t_start_ms: int
    t_end_ms: int
    movement_type: MovementType
    intensity: float = 0.0  # 0-1 scale
    confidence: float = 1.0


@dataclass
class MotionAnalysis:
    """Complete motion analysis result."""
    has_motion: bool = False
    dominant_movement: Optional[MovementType] = None
    segments: List[MotionSegment] = field(default_factory=list)
    avg_flow_magnitude: float = 0.0
    peak_flow_magnitude: float = 0.0
    static_ratio: float = 0.0  # Ratio of static frames


# =============================================================================
# Audio Analysis Types
# =============================================================================


@dataclass
class AudioAnalysis:
    """Audio analysis result from librosa."""
    has_audio: bool = False
    bpm: Optional[float] = None
    onset_timestamps: List[float] = field(default_factory=list)  # Seconds
    beat_timestamps: List[float] = field(default_factory=list)   # Seconds
    rms_db: Optional[float] = None  # Average loudness
    spectral_centroid: Optional[float] = None  # Brightness measure
    duration_seconds: float = 0.0


# =============================================================================
# Provenance Types
# =============================================================================


@dataclass
class UnifiedPassProvenance:
    """Provenance tracking for Unified Pass (Pass 1)."""
    model_id: str = ""
    prompt_version: str = ""
    media_resolution: str = "low"
    hook_clip_seconds: float = 4.0
    hook_clip_fps: float = 10.0
    full_video_fps: float = 1.0
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    total_tokens: int = 0
    audio_context_injected: bool = False
    motion_context_injected: bool = False


# =============================================================================
# Exports
# =============================================================================

__all__ = [
    # Enums
    "AnalysisPriority",
    "MeasurementMethod",
    "MovementType",
    # Pass 1 Types
    "MeasurementSpecLLM",
    "AnalysisPointSeedLLM",
    "AnalysisPlanLLM",
    "EntityHintLLM",
    "MicrobeatLLM",
    "HookAttributesLLM",
    "HookGenomeLLM",
    "SceneLLM",
    "CapsuleBriefLLM",
    "UnifiedPassLLMOutput",
    "UnifiedPassProvenance",
    # Pass 2 Types
    "MetricResult",
    "PointMeasurement",
    "CVMeasurementResult",
    "CVPassProvenance",
    # Motion Types
    "MotionSegment",
    "MotionAnalysis",
    # Audio Types
    "AudioAnalysis",
]
