#!/usr/bin/env python3
"""
Generate App/Dimension color tokens from AppRegistry YAML.

Usage:
  python scripts/generate_app_colors.py \
    --input config/apps/content/dimensions \
    --output tokens/app_colors.json
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any

import yaml


def stable_hue(seed: str) -> int:
    digest = hashlib.md5(seed.encode("utf-8")).hexdigest()
    value = int(digest[:8], 16)
    return value % 360


def load_yaml(path: Path) -> Dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def normalize_app_id(name: str) -> str:
    return name.strip().upper()


def slugify_app_id(app_id: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", app_id.lower()).strip("-")
    return slug


def format_number(value: float) -> str:
    text = f"{value:.3f}"
    return text.rstrip("0").rstrip(".")


def oklch_value(lightness: float, chroma: float, hue: int) -> str:
    return f"oklch({format_number(lightness)} {format_number(chroma)} {hue})"


def build_css(colors: Dict[str, Any], generated_at: str) -> str:
    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by scripts/generate_app_colors.py */")
    lines.append(f"/* Generated: {generated_at} */")
    lines.append("")
    lines.append(":root {")
    for app_id in sorted(colors.keys()):
        data = colors[app_id]
        slug = slugify_app_id(app_id)
        light = oklch_value(data["L"]["light"], data["chroma"], data["hue"])
        dark = oklch_value(data["L"]["dark"], data["chroma"], data["hue"])
        lines.append(f"  --app-color-{slug}-light: {light};")
        lines.append(f"  --app-color-{slug}-dark: {dark};")
        lines.append(f"  --app-color-{slug}: {light};")
    lines.append("}")
    lines.append("")
    lines.append(".dark {")
    for app_id in sorted(colors.keys()):
        data = colors[app_id]
        slug = slugify_app_id(app_id)
        dark = oklch_value(data["L"]["dark"], data["chroma"], data["hue"])
        lines.append(f"  --app-color-{slug}: {dark};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate app color tokens from YAML")
    parser.add_argument("--input", required=True, help="Directory with app YAML files")
    parser.add_argument("--output", required=True, help="Output JSON path")
    parser.add_argument("--css-output", help="Optional CSS output path")
    parser.add_argument("--frontend-output", help="Optional frontend JSON output path")
    args = parser.parse_args()

    input_dir = Path(args.input).resolve()
    output_path = Path(args.output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    colors: Dict[str, Any] = {}
    for yaml_path in sorted(input_dir.glob("*.yaml")):
        data = load_yaml(yaml_path)
        name = data.get("metadata", {}).get("name")
        if not name:
            continue
        app_id = normalize_app_id(name)
        hue = stable_hue(app_id)
        colors[app_id] = {
            "hue": hue,
            "chroma": 0.18,
            "L": {"light": 0.52, "dark": 0.64},
            "source": str(yaml_path.relative_to(input_dir.parent.parent.parent)),
        }

    generated_at = datetime.now(timezone.utc).isoformat()
    payload = {
        "generated_at": generated_at,
        "source": "config/apps/content/dimensions/*.yaml",
        "strategy": "stable-hash-hue + fixed chroma/lightness",
        "app_colors": colors,
    }

    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {output_path}")

    if args.css_output:
        css_path = Path(args.css_output).resolve()
        css_path.parent.mkdir(parents=True, exist_ok=True)
        css_payload = build_css(colors, generated_at)
        css_path.write_text(css_payload, encoding="utf-8")
        print(f"Wrote {css_path}")

    if args.frontend_output:
        frontend_path = Path(args.frontend_output).resolve()
        frontend_path.parent.mkdir(parents=True, exist_ok=True)
        frontend_payload = {
            "generated_at": generated_at,
            "source": payload["source"],
            "strategy": payload["strategy"],
            "app_colors": {
                app_id: {
                    **data,
                    "slug": slugify_app_id(app_id),
                    "css_var": f"--app-color-{slugify_app_id(app_id)}",
                    "css_var_light": f"--app-color-{slugify_app_id(app_id)}-light",
                    "css_var_dark": f"--app-color-{slugify_app_id(app_id)}-dark",
                }
                for app_id, data in colors.items()
            },
        }
        frontend_path.write_text(
            json.dumps(frontend_payload, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        print(f"Wrote {frontend_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
